name: Package

on:
  workflow_dispatch:

jobs:
  package:
    name: Package and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ›’ Checkout
        uses: actions/checkout@v3

      - name: ğŸ Get Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: ğŸ› ï¸ Setup Build
        run: python -m pip install build --user

      - name: ğŸ› ï¸ Build Package
        run: python -m build --sdist --wheel --outdir dist/ src/

      - name: ğŸ“¦ Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
